name: referee-fyi-production

on:
  push:
    branches:
      - main

jobs:
  referee-fyi:
    runs-on: ubuntu-latest
    environment: production
    name: production
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: "24.x"
      - run: npm ci
      - run: npm run build
        env:
          CI: true
          VITE_REFEREE_FYI_BUILD_MODE: ${{vars.VITE_REFEREE_FYI_BUILD_MODE}}
          VITE_REFEREE_FYI_ENABLE_SENTRY: ${{vars.VITE_REFEREE_FYI_ENABLE_SENTRY}}
          VITE_REFEREE_FYI_RULES_SERVER: ${{vars.VITE_REFEREE_FYI_RULES_SERVER}}
          VITE_REFEREE_FYI_SHARE_SERVER: ${{vars.VITE_REFEREE_FYI_SHARE_SERVER}}
          VITE_REFEREE_FYI_ROBOTEVENTS_SERVER: ${{vars.VITE_REFEREE_FYI_ROBOTEVENTS_SERVER}}
          VITE_LOGSERVER_TOKEN: ${{ secrets.VITE_LOGSERVER_TOKEN }}
          VITE_ROBOTEVENTS_TOKEN: ${{ secrets.VITE_ROBOTEVENTS_TOKEN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      - uses: cloudflare/wrangler-action@v3
        with:
          workingDirectory: "apps/referee-fyi"
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: "worker/sync"
          environment: "production"
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: "worker/rules"
          environment: "production"
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: "worker/events"
          environment: "production"
